name: aura_sphere_360
description: Immersive 360Â° panorama and video viewer for Flutter. Display spherical images and videos with touch controls, sensor controls, and smooth 30 FPS playback. Perfect for VR experiences and 360Â° media.
version: 1.0.0
homepage: https://github.com/Camertronix-Cm/aura_sphere_360
repository: https://github.com/Camertronix-Cm/aura_sphere_360
issue_tracker: https://github.com/Camertronix-Cm/aura_sphere_360/issues

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cube: ^0.1.1
  dchs_motion_sensors: ^2.0.1
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


